language: go
go:
  - 1.6

sudo: false

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  - provider: s3
    access_key_id:
      secure: "oZ2B19JGpwCdhL4B/FyPUx99WQTSQY+0ozfiqE0yKKRFoont2ZJjWVLnSLdxebj3wl5/kc1UinKHpIjxv5ewQiaJELnEfMtLT8dX5UkjuJzxLSOQed9eStMxjGonvJT4o80QANHRb9QnUdWO0xshwRKvyes+al2+MhXrFfUJUzMkQJ5QX6FA3lzoevltRRKOsTLjAH7UCAajjqra9d6wss2gsRPkxKd0CcjUvyhNkgC1pKZff83qWx2cP6hTx5Txo4tTd/QzxY632R/LjIE3pdw4w5ejYu1e//9rNwiRwAwCwkXwDeJ7CjASKMLIMU1/WXNKr4ndU0RaIi7xEQCp1uzzIB7Lu/UOx/sE4N9mPHB8LNDOdMwGxlmwdJ98qNZgGeV/B7+Q3jxCS+2/V7QUAoEMFo9MzCY1Wb3p7oj9cAimMLHk9ZGw+OAw2TN7ci0FY6oUXTTCVp70FMi+ftJFc7830aCSN/FerppYEWqgA/DGVraCi12Sylbqm+8GTzHF3tqZkbME2XZG/G6TwpqmUMtWwXiqFQRPIh06NgEITUPW2ZEhIOd+ankFw3ulyuZKP6SGzNiiFbHIYg1l7epEPtT/4hvetaU/m4koPh7H4q8RPVyfXu6+QG5xGlxOrO7qXEQwOEr1xyNl3LtEzhJKk1uNBwQ/zfvGCLZ0W2DfIy0="
    secret_access_key:
      secure: "m7QIWSGI6kkcUe+PgHYnWG3bd2Uj70Xxs3BJFliKqS5Dq1ygUi9c2Z4/6gEOQ6b2/YvXPRbNJbtBdtgML5wSz2mBYJH0IEPRlmzFu5CENHMTcfQ1NJNjXgVNKc5NysBLY9O01vhGV7P0zaREF9yvxVV+XLa5OKqhOTaW/3KmAd7YYIBz2gjlLWrpFwphMi/ioztlBxcR9PfeWZTmkKtV+temY4iOsLKtw8CLHySNxT2Vb3lRI5uJSv9VMJUZ+OqSqYJI55hhUrW4ETDx10zKJMuLIaem8g1VnUPZzced7flkB8JRpRslCIqcCKEcVQFFMANbTNDbx/Z2w56PFO77dER8CiH5UXWosqeR89XF/ytu5cNmvimbHMENVIAhtz2Tmz7ff4NKTFQaSCw/QC0Ii9b5CMlZSLT6CPGIoPzduMk0vfUTpUocHgJvINYv6HpCJyaBrWsBnRwnQSfwNmxD8tw+GdyJfOWPmhSdJ/GbWRh0gNKio+29eH2wRekqnm/mvY30CsCDkJdBQKqaFUgmjZiwKcDVuYzowHP6awHW1DME6A74lO5LNUOMUh6w3muk7mOC1NBp2X8m+VMSZDBZzta7ExebZUYPwPGXMkqovE0iVdIxYqgLWNjDtBXSbDZ9Uq0i/3VBmw4NQTw5bxxV6teRDfhBukG/DBVAVoPIoCU="
    bucket:
      secure: "dJnKOplm3LpPRwRd+r2FcLnWd5G/K9MHq2jbcVjuL3+6cpmV0SypaCSHdKFxRo2JK8iy8yoGPX1vod4bLvngnMyK8JgCFDumAG+GvEtpqze8jLS9KjeWXkBb/uHb9rGq/0JEPng7BRk+25RWYr1VGSuWktWJM+LHze8sz5JQ1IwwPlD9+NH6lSzjojd8jHm2/ArTkO1ZwPNBsxTPVR6jRZIxz2t6OfX9JNvZVRyMyhYvaO9Pt7RxhdjJBocZypppO8alP25qdhzMeFOx5RSIqvUlcdVlWXw4iYybKMrCM3f+7XJ6UclHh15S+Gk+jOCBvWqWBbzyV12SLlPRJrBM02JLh7yjWEdQZ8Z+VTEFm4oZqcjQQLIfw71Tjqpz4C/J+ZXTuqGH+mGz7tP2TVkCGPA+l/Hd5C2h7u8zLvXiGbiSgVa77sYQJsxuZsX4ymuw324ndCtY2ukDCfbutE8tQYhHPiGFdEOc3FDxjy4cjkxTxDFSGc1CDVpeamL9R7AmRkzGQLLNfAW7fntb94geh6KouLkswaZ1i2UdyT/7JXT62LKMvk/2NGfe9o8y0c7K84KUVY/YVOGRQZddYrQlHNXOYTp7g38q9tLw+PGRp0EXEkJzO8XGqCTI8L+8AsAWLCF6LjE0/1/V8nXTo+s1pUmgoMJ4iJtyGNNJMSCxU+o="
    region: eu-west-1
    local_dir: public
    skip_cleanup: true
